language: objective-c

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - FRAMEWORK_NAME="Encryption"
    - UPDATE_DOCS="true"

matrix:
  include:
    - osx_image: xcode10.2
      env: SDK="macosx10.14" SWIFT_VERSION="5.0" ACTION="test"

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild
      "$ACTION"
      -project "$FRAMEWORK_NAME.xcodeproj"
      -scheme "$FRAMEWORK_NAME"
      -sdk "$SDK"
      -configuration Debug
      ONLY_ACTIVE_ARCH=YES
      GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES
      GCC_GENERATE_TEST_COVERAGE_FILES=YES
      SWIFT_VERSION=$SWIFT_VERSION;

after_success:
  - bash <(curl -s https://codecov.io/bash) -J Encryption
  - test $TRAVIS_PULL_REQUEST == "false" &&
    test $TRAVIS_BRANCH == "master" &&
    test $UPDATE_DOCS == "true" &&
    .scripts/update-gh-pages